server:
  port: 8084
  servlet:
    context-path: "/${spring.application.api-version}"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bnk
    username: root
    password: password@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: 'update'
    generate-ddl: true
    show-sql: true

  application:
    name: ACCOUNT-SERVICE
    api-version: "v1"


logging:
  file:
    name: account-app-log.log
    path: /var/log
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR