server:
  port: 8083
  servlet:
    context-path: "/${spring.application.api-version}"

  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bnk
    username: root
    password: password@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: 'update'
#      ddl-auto: 'create-drop'
    generate-ddl: true
    show-sql: true



  application:
    name: CUSTOMER-SERVICE
    api-version: "v1"


logging:
  file:
    name: cust-app-log.log
    path: /var/log
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR